name: rustfmt

on:
  push:
    branches: [main, release]
    paths-ignore: [docs/**, README.md, .cspell.json, .gitignore]
  pull_request:
  workflow_dispatch:


jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Run rustfmt
        run: make format-check