name: rustfmt

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, edited]
  workflow_dispatch:


jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Run rustfmt
        run: make format-check